In [17]:
from beamline_29 import IEX

In [18]:
import time
import matplotlib.pyplot as plt
import math

In [19]:
%matplotlib widget

In [20]:
IEX.run()

17570

In [21]:
IEX.sample()
IEX.run()

0

In [22]:
IEX.run()

0

In [23]:
IEX.center()
IEX.run()

68412

Things are working as expected

In [24]:
%%timeit
IEX.sample()
IEX.run()

710 ms ± 74.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
%prun IEX.run()

         36 function calls in 0.860 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        6    0.808    0.135    0.808    0.135 {method 'traceOE' of 'Beam' objects}
        1    0.046    0.046    0.046    0.046 {method 'genSource' of 'Beam' objects}
        1    0.004    0.004    0.004    0.004 {method 'copy' of 'numpy.ndarray' objects}
        1    0.001    0.001    0.860    0.860 beamline_29.py:297(run)
        1    0.001    0.001    0.005    0.005 ShadowLibExtensions.py:399(nrays)
        1    0.000    0.000    0.001    0.001 beamline_29.py:108(resetBeamline)
        1    0.000    0.000    0.000    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
        1    0.000    0.000    0.004    0.004 ShadowLibExtensions.py:180(getshonecol)
        4    0.000    0.000    0.000    0.000 {built-in method numpy.array}
        1    0.000    0.000    0.860    0.860 {built-in method builtins.exec}
        

In [35]:
rays = []
t1 = time.time()
for i in range(3000):
    IEX.sample()
    rays.append(IEX.run())
    print('\r Iteration %d' % i, end = ' ')
    
print(' ')
t2 = time.time()
print('Duration: %f' % (t2 - t1))

 Iteration 2999  
Duration: 2017.745414


In [53]:
fig, axs = plt.subplots(1, 1, tight_layout=True)

# We can set the number of bins with the `bins` kwarg
#axs.title = '1000 configs, full range'
#axs.xtitle = "Number of rays"
axs.set(title = '3k Configs, Full range',
        xlabel = 'Number of rays')
axs.hist(rays, bins=20)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([2074.,  161.,  109.,   94.,   50.,   67.,   53.,   45.,   38.,
          37.,   32.,   38.,   40.,   28.,   26.,   37.,   19.,   26.,
          15.,   11.]),
 array([    0.  ,  4696.55,  9393.1 , 14089.65, 18786.2 , 23482.75,
        28179.3 , 32875.85, 37572.4 , 42268.95, 46965.5 , 51662.05,
        56358.6 , 61055.15, 65751.7 , 70448.25, 75144.8 , 79841.35,
        84537.9 , 89234.45, 93931.  ]),
 <a list of 20 Patch objects>)

Reducing sampling region by 90%

In [37]:
IEX.sRange = IEX.sRange *0.1

In [38]:
rays2 = []
t1 = time.time()
for i in range(3000):
    IEX.sample()
    rays2.append(IEX.run())
    print('\r Iteration %d' % i, end = ' ')
    
print(' ')
t2 = time.time()
print('Duration: %f' % (t2 - t1))

 Iteration 2999  
Duration: 2005.083708


In [52]:
fig, axs = plt.subplots(1, 1, tight_layout=True)

# We can set the number of bins with the `bins` kwarg
axs.set(title = '3k Configs, 0.1x Range',
        xlabel = 'Number of rays')
axs.hist(rays2, bins=20)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([  6.,   1.,  10.,  14.,  29.,  42.,  38.,  61.,  66., 108., 138.,
        253., 371., 372., 306., 334., 311., 250., 208.,  82.]),
 array([50280. , 51410.3, 52540.6, 53670.9, 54801.2, 55931.5, 57061.8,
        58192.1, 59322.4, 60452.7, 61583. , 62713.3, 63843.6, 64973.9,
        66104.2, 67234.5, 68364.8, 69495.1, 70625.4, 71755.7, 72886. ]),
 <a list of 20 Patch objects>)

Setting window to 0.25 of original

In [40]:
IEX.sRange = IEX.sRange *2.5

In [41]:
rays3 = []
t1 = time.time()
for i in range(3000):
    IEX.sample()
    rays3.append(IEX.run())
    print('\r Iteration %d' % i, end = ' ')
    
print(' ')
t2 = time.time()
print('Duration: %f' % (t2 - t1))

 Iteration 2999  
Duration: 1997.787697


In [51]:
fig, axs = plt.subplots(1, 1, tight_layout=True)

# We can set the number of bins with the `bins` kwarg
axs.set(title = '3k Configs, 0.25x Range',
        xlabel = 'Number of rays')
axs.hist(rays3, bins=20)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([  7.,  18.,  29.,  38.,  55.,  61.,  62.,  83., 121., 126., 150.,
        213., 256., 287., 317., 326., 297., 241., 221.,  92.]),
 array([ 8996.  , 12489.45, 15982.9 , 19476.35, 22969.8 , 26463.25,
        29956.7 , 33450.15, 36943.6 , 40437.05, 43930.5 , 47423.95,
        50917.4 , 54410.85, 57904.3 , 61397.75, 64891.2 , 68384.65,
        71878.1 , 75371.55, 78865.  ]),
 <a list of 20 Patch objects>)

In [43]:
IEX.sRange = IEX.sRange * 4.0 * 0.4 # now at 0.4 of original

In [44]:
IEX.sRange

array([[[-8.160e+00,  8.160e+00],
        [-8.000e+00,  8.000e+00],
        [-6.000e-01,  6.000e-01],
        [-4.000e-03,  4.000e-03],
        [-2.480e-01,  2.480e-01],
        [-8.000e+00,  8.000e+00]],

       [[-9.160e+00,  9.160e+00],
        [-8.000e+00,  8.000e+00],
        [-1.000e+00,  1.000e+00],
        [-4.000e-03,  4.000e-03],
        [-7.200e-02,  7.200e-02],
        [-8.000e+00,  8.000e+00]],

       [[-6.440e+00,  6.440e+00],
        [-8.000e+00,  8.000e+00],
        [-3.600e-01,  3.600e-01],
        [-8.000e-03,  8.000e-03],
        [-1.480e-01,  1.480e-01],
        [-8.000e+00,  8.000e+00]],

       [[-5.440e+00,  5.440e+00],
        [-1.400e+00,  1.400e+00],
        [-4.000e-01,  4.000e-01],
        [-8.000e-03,  8.000e-03],
        [-1.400e-01,  1.400e-01],
        [-2.996e+00,  2.996e+00]],

       [[-3.320e+00,  3.320e+00],
        [-1.680e+01,  1.680e+01],
        [-2.000e+00,  2.000e+00],
        [-1.600e-01,  1.600e-01],
        [-1.288e+00,  1.288e+00],
      

In [45]:
rays4 = []
t1 = time.time()
for i in range(3000):
    IEX.sample()
    rays4.append(IEX.run())
    print('\r Iteration %d' % i, end = ' ')
    
print(' ')
t2 = time.time()
print('Duration: %f' % (t2 - t1))

 Iteration 2999  
Duration: 2001.688273


In [50]:
fig, axs = plt.subplots(1, 1, tight_layout=True)

# We can set the number of bins with the `bins` kwarg
axs.set(title = '3k Configs, 0.4x Range',
        xlabel = 'Number of rays')
axs.hist(rays4, bins=20)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([103., 116., 124., 121., 139., 135., 136., 177., 150., 179., 190.,
        215., 183., 203., 167., 205., 170., 149., 100.,  38.]),
 array([8.30000e+01, 4.25120e+03, 8.41940e+03, 1.25876e+04, 1.67558e+04,
        2.09240e+04, 2.50922e+04, 2.92604e+04, 3.34286e+04, 3.75968e+04,
        4.17650e+04, 4.59332e+04, 5.01014e+04, 5.42696e+04, 5.84378e+04,
        6.26060e+04, 6.67742e+04, 7.09424e+04, 7.51106e+04, 7.92788e+04,
        8.34470e+04]),
 <a list of 20 Patch objects>)

In [47]:
IEX.pos

array([[ 4.49842512e+00,  0.00000000e+00,  0.00000000e+00,
         8.51957821e-06,  0.00000000e+00,  0.00000000e+00],
       [ 2.44427238e+00,  0.00000000e+00,  0.00000000e+00,
        -1.27767337e-03,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         6.43706878e-03,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.33749439e-03,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.78986972e+00,  0.00000000e+00,
        -1.11017120e-03, -1.06124179e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.17808644e+00,  0.00000000e+00,
        -4.80408694e-02,  9.61734954e-01,  0.00000000e+00]])

In [48]:
IEX.pos[IEX.mask == 1]

array([ 4.49842512e+00,  8.51957821e-06,  2.44427238e+00, -1.27767337e-03,
        6.43706878e-03,  4.33749439e-03, -1.78986972e+00, -1.11017120e-03,
       -1.06124179e+00,  1.17808644e+00, -4.80408694e-02,  9.61734954e-01])

In [54]:
rays5 = []
positioners = []

t1 = time.time()
for i in range(100000):
    IEX.sample()
    rays5.append(IEX.run())
    positioners.append(IEX.pos[IEX.mask == 1])
    print("\r Iteration {:} -- run duration {:1d} s".format(i, math.ceil(time.time()-t1)), end = ' ')
    
print(' ')
t2 = time.time()
print('Duration: %f' % (t2 - t1))

fig, axs = plt.subplots(1, 1, tight_layout=True)
axs.set(title = '100k Configs, 0.4x Range',
        xlabel = 'Number of rays')
axs.hist(rays5, bins=20)

 Iteration 99999 -- run duration 67638 s  
Duration: 67637.240258


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([3438., 4107., 4309., 4370., 4523., 4889., 4977., 5253., 5361.,
        6015., 6550., 7233., 7144., 6587., 6010., 5526., 4974., 4311.,
        3204., 1219.]),
 array([4.800000e+01, 4.242350e+03, 8.436700e+03, 1.263105e+04,
        1.682540e+04, 2.101975e+04, 2.521410e+04, 2.940845e+04,
        3.360280e+04, 3.779715e+04, 4.199150e+04, 4.618585e+04,
        5.038020e+04, 5.457455e+04, 5.876890e+04, 6.296325e+04,
        6.715760e+04, 7.135195e+04, 7.554630e+04, 7.974065e+04,
        8.393500e+04]),
 <a list of 20 Patch objects>)

In [47]:
positioners[0].shape

(12,)

In [48]:
len(rays5)

100000

In [49]:
import pickle

In [50]:
data = {'y': rays5, 'x':positioners}

In [53]:
data['x'][1]

array([ 4.11249165e-01,  3.72877390e-03, -5.42909342e+00,  1.34745851e-03,
        2.71554575e-03,  4.17568269e-03, -4.53801650e+00, -5.52804760e-02,
        1.16616223e+00,  5.21392605e-01,  3.74671810e-01, -6.61753323e-01])

In [58]:
rays5[0], rays5[1], positioners[1]

(62184,
 7104,
 array([ 4.11249165e-01,  3.72877390e-03, -5.42909342e+00,  1.34745851e-03,
         2.71554575e-03,  4.17568269e-03, -4.53801650e+00, -5.52804760e-02,
         1.16616223e+00,  5.21392605e-01,  3.74671810e-01, -6.61753323e-01]))

In [59]:
pickle.dump(data, open("IEX_100k_04w.pkl", "wb"))